nessie.version.store.type=IN_MEMORY
nessie.catalog.default-warehouse=main
nessie.catalog.warehouses.main.location=s3://manufacturing-iceberg/warehouse
nessie.catalog.service.s3.default-options.endpoint=http://minio:9000
nessie.catalog.service.s3.default-options.path-style-access=true
nessie.catalog.service.s3.default-options.access-key=urn:nessie-secret:quarkus:minio-creds
minio-creds.name=minioadmin
minio-creds.secret=minioadmin
